### ISSUE TITLE
Ottimo lavoro!

### ISSUE THREAD

**Issue by iccicci** [Biuni/rt-italy#1]
Ciao Gianluca,

scusa se scrivo qui ma è l'unica via che sono stato capace di trovare per raggiungerti.
Se posso rubarti 10 minuti vorrei parlarti in privato su https://twitter.com/DanieleiCC .

Spero a presto,
Daniele

**Comment by Biuni** [comment]
Tranquillo, nessun problema. Ti ho contattato su Twitter.
